ckd_test_data = [
    {
        "id": 1,
        "age": 48,
        "bp": 80,
        "sg": 1.020,
        "al": 1,
        "su": 0,
        "rbc": "normal",
        "pc": "normal",
        "pcc": "present",
        "ba": "not present",
        "bgr": 121,
        "bu": 36,
        "sc": 1.2,
        "sod": 135,
        "pot": 4.0,
        "hemo": 15.4,
        "pcv": 44,
        "wc": 7800,
        "rc": 5.2,
        "htn": "yes",
        "dm": "no",
        "cad": "no",
        "appet": "good",
        "pe": "no",
        "ane": "no"
    },
    {
        "id": 2,
        "age": 60,
        "bp": 90,
        "sg": 1.015,
        "al": 2,
        "su": 3,
        "rbc": "abnormal",
        "pc": "abnormal",
        "pcc": "present",
        "ba": "present",
        "bgr": 133,
        "bu": 49,
        "sc": 1.8,
        "sod": 139,
        "pot": 5.2,
        "hemo": 11.2,
        "pcv": 32,
        "wc": 6700,
        "rc": 3.9,
        "htn": "yes",
        "dm": "yes",
        "cad": "yes",
        "appet": "poor",
        "pe": "yes",
        "ane": "yes"
    },
    {
        "id": 3,
        "age": 35,
        "bp": 70,
        "sg": 1.025,
        "al": 0,
        "su": 0,
        "rbc": "normal",
        "pc": "normal",
        "pcc": "not present",
        "ba": "not present",
        "bgr": 105,
        "bu": 20,
        "sc": 0.8,
        "sod": 140,
        "pot": 4.5,
        "hemo": 14.3,
        "pcv": 41,
        "wc": 8100,
        "rc": 4.8,
        "htn": "no",
        "dm": "no",
        "cad": "no",
        "appet": "good",
        "pe": "no",
        "ane": "no"
    }
]